apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: java-demo-vn
  namespace: testing-1
spec:
  podSelector:
    matchLabels:
      app: java-demo
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: java-demo.testing-1.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1
  namespace: testing-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
        - name: app
          image: 672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "COLOR"
              value: "v1"

---
apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: testing-1
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: java-demo
