apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: testing-1
  name: java-demo-vr
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: java-demo-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: java-demo-vn
              weight: 1
