apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: testing-1
  name: java-demo-vr-1
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: java-demo-route-1
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: java-demo-vn-1
              weight: 1
